<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.xiaoxu</groupId>
		<artifactId>java_arsenal</artifactId>
		<version>1.0</version>
	</parent>

	<artifactId>consumer_boot</artifactId>
	<version>1.0</version>
	<packaging>jar</packaging>
	<name>consumer_boot</name>
	<description>web_boot_consumer</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
<!--		traceId-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-logging</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>


<!--		rabbitmq-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-amqp</artifactId>
		</dependency>

		<!--		<dependency>-->
<!--			<groupId>org.apache.dubbo</groupId>-->
<!--			<artifactId>dubbo-spring-boot-starter</artifactId>-->
<!--			<version>3.2.0</version>-->
<!--		</dependency>-->

<!--		<dependency>-->
<!--			<groupId>org.apache.curator</groupId>-->
<!--			<artifactId>curator-framework</artifactId>-->
<!--			<version>5.5.0</version>-->
<!--		</dependency>-->

<!--		<dependency>-->
<!--			<groupId>org.apache.curator</groupId>-->
<!--			<artifactId>curator-recipes</artifactId>-->
<!--			<version>5.5.0</version>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.curator</groupId>-->
<!--			<artifactId>curator-x-discovery</artifactId>-->
<!--			<version>5.5.0</version>-->
<!--		</dependency>-->

		<!--定义写的dubbo接口 的jar包-->
<!--		<dependency>-->
<!--			<groupId>org.xiaoxu</groupId>-->
<!--			<artifactId>web_boot</artifactId>-->
<!--			<version>0.0.1-SNAPSHOT</version>-->
<!--		</dependency>-->







	</dependencies>


	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
