server:
  port: 23010
spring:
  application:
    name: server-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/ito_op
    username: root
    password: xiaoxu
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: NFTurbo666


logging:
  level:
    root: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
