<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.xiaoxu</groupId>
        <artifactId>three-major-mq-service</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>rocketmq-service</artifactId>
    <packaging>jar</packaging>

    <name>rocketmq-service</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>2.7.18</version>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.7.18</version>
        </dependency>


        <dependency>
        <groupId>org.apache.rocketmq</groupId>
        <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.3.5</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.rocketmq</groupId>
                    <artifactId>rocketmq-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>org.apache.rocketmq</groupId>-->
<!--            <artifactId>rocketmq-spring-boot-starter</artifactId>-->
<!--            <version>2.3.5</version>-->
<!--            <exclusions>-->

<!--                            <exclusion>-->
<!--                                <groupId>org.apache.rocketmq</groupId>-->
<!--                                <artifactId>rocketmq-client</artifactId>-->
<!--                            </exclusion>-->
<!--                        </exclusions>-->
<!--        </dependency>-->


<!--&lt;!&ndash;        <dependency>&ndash;&gt;-->
<!--&lt;!&ndash;            <groupId>org.apache.rocketmq</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;            <artifactId>rocketmq-spring-boot-starter</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;            <version>2.3.5</version>&ndash;&gt;-->
<!--&lt;!&ndash;            <exclusions>&ndash;&gt;-->
<!--&lt;!&ndash;                <exclusion>&ndash;&gt;-->
<!--&lt;!&ndash;                    <groupId>org.apache.rocketmq</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                    <artifactId>rocketmq-client</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                </exclusion>&ndash;&gt;-->
<!--&lt;!&ndash;            </exclusions>&ndash;&gt;-->
<!--&lt;!&ndash;        </dependency>&ndash;&gt;-->

        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
            <version>5.3.0</version>
        </dependency>
    </dependencies>
</project>
