server:
  port: 16888
spring:
  application:
    name: server-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.131:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: server-user
          uri: lb://server-user
          predicates:
            - Path=/api/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
      globalcors:
        cors-configurations:
          '[/**]': # '[/**]' 匹配所有路径
            allowed-origins: "http://localhost:5173" # 允许的前端源地址，不能用*如果allowCredentials为true
            allowed-methods: # 允许的HTTP方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*" # 允许所有的请求头
            allow-credentials: true # 是否允许携带Cookie
            max-age: 3600 # 预检请求的缓存时间（秒）
  data:
    redis:
      host: 192.168.200.131
      port: 6379
      password: NFTurbo666
      database: 0
      timeout: 10000ms
logging:
  level:
    root: info