server:
  port: 16888
spring:
  application:
    name: server-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: server-user
          uri: lb://server-user
          predicates:
            - Path=/user/**
        - id: server-order
          uri: lb://server-order
          predicates:
            - Path=/order/**
          filters:
          - PrefixPath=/order