server:
  port: 9191
spring:
  datasource:

#      url: jdbc:mysql://127.0.0.1:3306/2026mysql_ds
      url: jdbc:mysql://127.0.0.1:3306/mysql2026
      username: root
      password: xiaoxu
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 32768
#      username: root
##      password:
#      database: 9

  application:
    name: co_insurance





mybatis:
  mapper-locations: classpath:mapper/*.xml
  #  驼峰映射
  configuration:
    map-underscore-to-camel-case: true
    #    开启sql日志审查
logging:
  level:
    root: info
    #   日志级别
    org.xiaoxu.mapper: debug




mybatis-plus: # 如果用的是 MP，建议统一写在 mybatis-plus 下
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true








