server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ito_op
    username: root
    password: xiaoxu
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: consumer-service


logging:
  level:
   root: info
