server:
  port: 9999

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ito_op
#    username: root
#    password: xiaoxu
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

spring:
  datasource:
    ds1:
      url: jdbc:mysql://127.0.0.1:3306/ito_op?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&socketTimeout=60000&connectTimeout=30000
      username: root
      password: xiaoxu
      driver-class-name: com.mysql.cj.jdbc.Driver
    ds2:
      url: jdbc:mysql://127.0.0.1:3333/ito_sap?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&socketTimeout=60000&connectTimeout=30000
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver


#dubbo:
#  application:
#    name: dubbo-provider
#  registry:
#    address: zookeeper://127.0.0.1:2181  # Zookeeper 地址
#  protocol:
#    name: dubbo
#    port: 20880
#  scan:
#    base-packages: org.xiaoxu.web_boot.service.dubbo

  # 其他你的配置...




#spring:
#  datasource:
#    dynamic:
#      primary: master  # 默认数据源
#      strict: false    # 严格模式，未匹配抛异常
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/ito_op
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          type: com.alibaba.druid.pool.DruidDataSource
#          username: root
#          password: xiaoxu
#        slave:
#          url: jdbc:mysql://124.221.151.196:3310/ito_sap
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          type: com.alibaba.druid.pool.DruidDataSource
#          username: root
#          password: 1234


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379
      password: redis
      database: 0
  mail:
    host: smtp.163.com
    username: tingqq7z@163.com
#    授权码
    password: THQNv5kfSEFfHEe7
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


##            #  搜索引擎
#  elasticsearch:
#    uris: http://localhost:9200
#    username: elastic
#    password: es123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  驼峰映射
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
   root: info

#   分布式文件服务
rustfs:
  endpoint: http://127.0.0.1:9000
  bucketName: master-xu
  accessKey: rustfsadmin
  secretKey: rustfsadmin




#监控
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  health:
    elasticsearch:
      enabled: true
      request-timeout: 10s
      # 下面这行是关键，指向你的用户名密码
      credentials:
        username: elastic
        password: es123456
