rocketmq:
  name-server: 192.168.200.131:9876
  #producer 配置项
  producer:
    group: demo-producer-group
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-async-failed: 2
    retry-times-when-send-failed: 2
    retry-next-server: false
    enable-msg-trace: true
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC
  consumer:
    listeners:
      test-consumer-group:
        topic1: false