server:
  port: 25255


spring:
  application:
    name: spring-practice-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql2026
    username: root
    password: xiaoxu
    driver-class-name: com.mysql.cj.jdbc.Driver


#mybatis-plus:
#  type-handlers-package: org.xiaoxu.handler
#  configuration:
#    map-underscore-to-camel-case: true

xxl:
  job:
    admin:
      address: http://192.168.200.131:8082/xxl-job-admin/
    executor:
      appName: xxl-job-executor-demo
      port: 9999
      logPath: /data/applogs/xxl-job/jobhandler
      logRetentionDays: 30
    accessToken: default_token