server:
  port: 25255


spring:
  application:
    name: spring-practice-service
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/practical_review
    username: root
    password: NFTurbo666
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 9
      host: 192.168.200.128
      password: NFTurbo666


#mybatis-plus:
#  type-handlers-package: org.xiaoxu.handler
#  configuration:
#    map-underscore-to-camel-case: true

xxl:
  job:
    admin:
      address: http://192.168.200.128:8082/xxl-job-admin/
    executor:
      appName:  xxl-job-executor
      port: 9999
      logPath: /data/applogs/xxl-job/jobhandler
      logRetentionDays: 30
    accessToken: default_token